"""
Project scaffolding.

Writes the project-side glue for a visual-regression workflow built on the ``webshot`` tool that
ships in the box. ``webshot`` itself is generic and already installed; what a project needs is a
small amount of application-specific glue plus somewhere to keep baselines, and that is what gets
copied out here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from importlib import resources
from pathlib import Path
from typing import TYPE_CHECKING
import shutil

if TYPE_CHECKING:
    from collections.abc import Iterator

__all__ = ('KINDS', 'ScaffoldResult', 'scaffold')

KINDS = ('noclip',)
"""Available scaffold kinds."""

SCENE_PLACEHOLDER = '@SCENE@'
"""Token in the template replaced with the caller's scene id."""

DEFAULT_SCENE = 'MyGame/Level1'
"""Scene id written when the caller does not supply one."""

_SUBDIR = 'viewer-tests'
"""Directory created inside the target for the harness."""

_EMPTY_DIRS = ('baselines', 'out')
"""Directories the harness writes into. ``baselines`` holds approved output and is effectively
source; ``out`` is regenerated by every capture."""

_EXECUTABLE = frozenset({'nc.mjs'})
"""Template files that must land executable."""

_DOCS = frozenset({'NEW_GAME.md'})
"""Template files written to the target root rather than into the harness directory."""


@dataclass
class ScaffoldResult:
    """What a scaffold run created or left alone."""
    skipped: list[Path] = field(default_factory=list)
    """Files that already existed and were not overwritten."""
    written: list[Path] = field(default_factory=list)
    """Files created."""


def _template_files(kind: str) -> Iterator[tuple[str, Path]]:
    root = resources.files('sbclaude') / 'templates' / kind
    with resources.as_file(root) as path:
        for item in sorted(Path(path).iterdir()):
            if item.is_file():
                yield item.name, item


def scaffold(target: Path,
             kind: str = 'noclip',
             *,
             scene: str | None = None,
             force: bool = False) -> ScaffoldResult:
    """
    Write the harness files for ``kind`` into ``target``.

    Existing files are never overwritten unless ``force`` is set: a baseline image or an edited
    ``views.json`` represents work that cannot be regenerated, so clobbering it silently would be
    worse than refusing.

    Parameters
    ----------
    target : Path
        Directory to scaffold into. Created if missing.
    kind : str
        Which scaffold to write; one of :data:`KINDS`.
    scene : str | None
        Scene id to write into the config, e.g. ``MyGame/Level1``.
    force : bool
        Overwrite files that already exist.

    Returns
    -------
    ScaffoldResult
        The files created and those skipped.

    Raises
    ------
    ValueError
        If ``kind`` is not a known scaffold.
    """
    if kind not in KINDS:
        msg = f'unknown scaffold kind {kind!r}; expected one of {", ".join(KINDS)}'
        raise ValueError(msg)
    result = ScaffoldResult()
    harness = target / _SUBDIR
    for name, source in _template_files(kind):
        dest = (target if name in _DOCS else harness) / name
        if dest.exists() and not force:
            result.skipped.append(dest)
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        if name.endswith('.json'):
            dest.write_text(source.read_text(encoding='utf-8').replace(
                SCENE_PLACEHOLDER, scene or DEFAULT_SCENE),
                            encoding='utf-8')
        else:
            shutil.copyfile(source, dest)
        if name in _EXECUTABLE:
            dest.chmod(0o755)
        result.written.append(dest)
    for name in _EMPTY_DIRS:
        # `out` is regenerated, but both must exist before the first capture, and an empty
        # `baselines` is the signal that nothing has been approved yet.
        (harness / name).mkdir(parents=True, exist_ok=True)
    return result
